// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilnjneboviaxhngqcbru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsbmpuZWJvdmlheGhuZ3FjYnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjYzNjUsImV4cCI6MjA2MDU0MjM2NX0.w1qB5xXLoKVE3tMDgBREfN2vmN1VXIuT5-gAQGL4MWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);